//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connector_Loading
    {
        public string ID { get; set; }
        public int LoadMax { get; set; }
        public int LoadingCount { get; set; }
        public int RunStatus { get; set; }
        public Nullable<System.DateTime> RunTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
    }
}
