//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VMGPSGateWayEntities : DbContext
    {
        public VMGPSGateWayEntities()
            : base("name=VMGPSGateWayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Connector_Info> Connector_Info { get; set; }
        public virtual DbSet<Connector_Loading> Connector_Loading { get; set; }
        public virtual DbSet<ConnectRecord> ConnectRecord { get; set; }
        public virtual DbSet<TE_Info> TE_Info { get; set; }
        public virtual DbSet<TE_Model> TE_Model { get; set; }
        public virtual DbSet<TE_ModelExtend> TE_ModelExtend { get; set; }
    }
}
